### ISSUE TITLE
Full authentication is required to access this resource

### ISSUE THREAD

**Issue by alexhui01** [BurningOKR/BurningOKR#24]
**Describe the bug**
Following the tomcat installation here, we got error when access to http://ip:8080 
>Full authentication is required to access this resource  

**To Reproduce**
1. follow the docs of tomcat installation and all the config
2. the application.yaml looks like 
```
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test?useSSL=false # For PostgreSQL Server
    username: okr
    password: halborn2021
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration/{vendor}
  mail:
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          auth: true
    test-connection: false
  messages:
    basename: messages
  pid:
    file: ./shutdown.pid


system:
  configuration:
    auth-mode: "local"
    api-endpoint: "/api"
    token-endpoint-prefix: ""
```
3 We can start the tomcat and can access to the http://ip/manager,   got error when hit the 8080 diretly
>Request URL: http://ip:8080/api/oAuthFrontendDetails
>Request Method: GET
>Status Code: 401 
> Remote Address: 127.0.0.1:15236
>Referrer Policy: strict-origin-when-cross-origin

**Expected behavior**
Loginto the OKR dashboard

**Screenshots**
<img width="1578" alt="Screen Shot 2021-06-02 at 3 11 22 PM" src="https://user-images.githubusercontent.com/77270506/120439227-dc26ec00-c3b4-11eb-84e2-a4cafc51edb2.png">

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser: Brave
 - Version: 1.24.86

**Additional context**

**Comment by alexhui01** [comment]
@mwilman Sorry to ping you for help.

**Comment by mwilman** [comment]
Did you have a previous version running?
Have you tried clearing the cookies/localstorage?

**Comment by halborn-steve** [comment]
HI @mwilman   I am workign with @alexhui01 on this issue to so we can set up the tool.
The front end works yes, but it Fails to connect to the API on the backend port 8080 because of the OAUTH.    We dont use AzureAD either... we use GSuite, but is tehre a way to just completly disconnect OAUTH and integrate our own ?  Thanks!!

**Comment by alexhui01** [comment]
Hi, @mwilman  I have cleared the cookie/localstorage or whatever. I have tried the previous version 1.1.0 since I noticed the latest release 1.1.1 just released several days ago. No lucky to get it fixed. Same error for authencation needed. 

BTW, we use local database instead of Azure AD. The only error I can see from the tomcat.  You can find the attached file as the logs.
[catalina.log](https://github.com/BurningOKR/BurningOKR/files/6588353/catalina.log)


> 2021-06-02 12:42:41,171 main ERROR Could not create plugin of type class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile: java.lang.IllegalStateException: ManagerFactory [org.apache.logg
ing.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@5b863697] unable to create manager for [C:/temp/burning-okr/burning-okr.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFi
leManager$FactoryData@2133814d[pattern=C:/temp/burning-okr/time-based-logs/%d{yyyy-MM-dd-hh}.log.zip, append=true, bufferedIO=true, bufferSize=8192, policy=CompositeTriggeringPolicy(policies=[TimeBasedTriggeringPolicy(nex
tRolloverMillis=0, interval=4, modulate=true)]), strategy=DefaultRolloverStrategy(min=1, max=5, useMax=true), advertiseURI=null, layout=%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n, filePermissions=null,
 fileOwner=null]] java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@5b863697] unable to create manager for [C:/temp/burning-okr/bu
rning-okr.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@2133814d[pattern=C:/temp/burning-okr/time-based-logs/%d{yyyy-MM-dd-hh}.log.zip, append=true, bufferedIO=true, bufferS
ize=8192, policy=CompositeTriggeringPolicy(policies=[TimeBasedTriggeringPolicy(nextRolloverMillis=0, interval=4, modulate=true)]), strategy=DefaultRolloverStrategy(min=1, max=5, useMax=true), advertiseURI=null, layout=%d{
yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n, filePermissions=null, fileOwner=null]]
        at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:115)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:115)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:188)
        at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:144)
        at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:60)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:958)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:898)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:890)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:513)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:237)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:249)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:261)

**Comment by alexhui01** [comment]
The application.yaml 
```
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test?useSSL=false # For PostgreSQL Server
    username: okr
    password: halborn2021
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration/{vendor}
  mail:
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          auth: true
    test-connection: false
  messages:
    basename: messages
  pid:
    file: ./shutdown.pid


system:
  configuration:
    auth-mode: "local"
    api-endpoint: "/api"
    token-endpoint-prefix: ""
```

**Comment by mwilman** [comment]
Thanks for the info. We had a holiday last week.
I will look into it today.

**Comment by mwilman** [comment]
It seems to have a problem with the logging / log4j plugin.
is the backend booting successfully?
Or is it a runtime error?

**Comment by alexhui01** [comment]
It's a runtime error. The backend can be started successfully with the log4j error.  The log error looks like to create a windows folder in c:\logxxx which doesn't matter.

**Comment by mwilman** [comment]
short update:
I won't have the time today to set up an environment with Tomcat. But I may have a solution. Try the following: 
change the token-endpoint-prefix to "/api".

So just swap the api-endpoint and token-endpoint like this:
```
system:
  configuration:
    auth-mode: "local"
    api-endpoint: ""
    token-endpoint-prefix: "/api"
```

A colleague told me that this is necessary to get it to work with tomcat. I have not been able to try it out today. I think tomorrow it will also time tight, but will give my best.
